# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Fract_config = debug
endif
ifeq ($(config),release)
  Fract_config = release
endif

PROJECTS := Fract

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Fract:
ifneq (,$(Fract_config))
	@echo "==== Building Fract ($(Fract_config)) ===="
	@${MAKE} --no-print-directory -C . -f Fract.make config=$(Fract_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Fract.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Fract"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"